name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/5almdggn9vygxkx6wpsxbv1h4z5p2qjj/install
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-fly-template
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --log-format raw -L build .#defaultDockerContainer.x86_64-linux
  staging:
    needs: build
    runs-on: ubuntu-latest
    concurrency: staging
    environment:
      name: staging
      url: https://nix-fly-template-staging.fly.dev/
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/5almdggn9vygxkx6wpsxbv1h4z5p2qjj/install
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-fly-template
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --log-format raw -L run .#deploy-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  production:
    needs: [ build, staging ]
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: production
      url: https://nix-fly-template.fly.dev/
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/5almdggn9vygxkx6wpsxbv1h4z5p2qjj/install
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-fly-template
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --log-format raw -L run .#deploy-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}